# joint_limits.yaml allows the dynamics properties specified in the URDF to
# be overwritten or augmented as needed.
#
# Specific joint properties can be changed with the keys
# [max_position, min_position, max_velocity, max_acceleration]
#
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 3
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.09
    has_acceleration_limits: true
    max_acceleration: 3
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.62
    has_acceleration_limits: true
    max_acceleration: 3
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.93
    has_acceleration_limits: true
    max_acceleration: 3
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 3
  joint_6:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6
